################################# Default configuration ###################
baseURL = 'https://dpx.netlify.app/'
title = "DataProjex"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

defaultContentLanguage = 'de'


############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### Deutsch Navigation ########################

[[Languages.de.menu.main]]
name = "Spectrum"
weight = 1
hasChildren = true

[[Languages.de.menu.main]]
parent = "Spectrum"
name = "DPX Analytics"
url = "#"
weight = 1

[[Languages.de.menu.main]]
parent = "Spectrum"
name = "DPX Perfomance"
url = "#"
weight = 2

[[Languages.de.menu.main]]
parent = "Spectrum"
name = "DPX Security"
url = "#"
weight = 3


[[Languages.de.menu.main]]
name = "Unternehmen"
url = "#unternehmen"
weight = 2

[[Languages.de.menu.main]]
name = "Karriere"
url = "404"
weight = 3

[[Languages.de.menu.main]]
name = "Kontakt"
url = "kontakt"
weight = 4

[[Languages.de.menu.main]]
name = "Support"
url = "support"
weight = 5

[[Languages.de.menu.main]]
name = "Mediathek"
url = "404"
weight = 6


################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 4

[[Languages.en.menu.main]]
name = "pricing"
url = "#pricing"
weight = 5

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7


[[Languages.en.menu.main]]
name = "Dropdown"
weight = 7
hasChildren = true

[[Languages.en.menu.main]]
parent = "Dropdown"
name = "Dropdown 1"
url = "#"
weight = 1

[[Languages.en.menu.main]]
parent = "Dropdown"
name = "Dropdown 2"
url = "#"
weight = 2

[[Languages.en.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8



############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ German Language ########################
[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/deutsch"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

