backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
collections:
  - name: "slider"
    label: "Slider"
    folder: "content/deutsch/slides"
    create: true
    fields:
      - { label: "Draft", name: "enable", widget: "boolean", default: true }
      - { label: "Background", name: "bg_image", widget: "image" }
      - { label: "Produkt", name: "hero_image", widget: "image" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "string" }
      - { label: "Animation from", name: "animation_from", widget: "string", default: "left" }
      - { label: "Button", name: "button", widget: "object", fields: [
          { label: "Enable", name: "enable", widget: "boolean", default: true },
          { label: "Label", name: "label", widget: "string" },
          { label: "Link", name: "link", widget: "string" }]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/deutsch/support/_index.md"
        name: "support"
        label: "Support Page"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
              { label: "Hintergrundbild", name: "bg_image", widget: "image"},
              { label: "Titel", name: "title", widget: "string"},
              { label: "Subline", name: "content", widget: "string" }]}
          - { label: "Linker Kasten", name: "linke_box", widget: "object", fields: [
              { label: "Headline", name: "headline", widget: "string"},
              { label: "Text", name: "copy", widget: "string"},
              { label: "Service Email VK Headline", name: "headlineservice", widget: "string"},
              { label: "Service Email VK", name: "servicevertragskundenemail", widget: "string"},
              { label: "Service Email Headline", name: "serviceemailHeadline", widget: "string"},
              { label: "Service Email", name: "serviceemail", widget: "string"},
              { label: "Service Tel Headline", name: "servicetelHeadline", widget: "string"},
              { label: "Service Tel", name: "servicetel", widget: "string"},
              { label: "Buttons", name: "buttons", widget: "list", fields: [
                { label: "Text Button", name: "name", widget: "string" },
                { label: "Link", name: "link", widget: "string" }]}]}

