backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
collections:
  - name: "startseite"
    label: "Startseite"
    files:
      - file: "data/de/slider.yml"
        label: "Slider"
        name: "slider"
        fields:
          - { label: "Slides", name: "slider_Item", widget: "list", fields: [
            { label: "Enable", name: "enable", widget: "boolean", default: true },
            { label: "Offset", name: "offset", widget: "number", default: 0, value_type: "int" },
            { label: "Background", name: "bg_image", widget: "image" },
            { label: "Produkt Image aktive", name: "hero_image_active", widget: "boolean", default: true },
            { label: "Produkt", name: "hero_image", widget: "image", default: "null"},
            { label: "Content", name: "copy", widget: "markdown" },
            { label: "Overlay", name: "overlay", widget: "boolean", default: false },
            { label: "Animation from", name: "animation_from", widget: "hidden", default: "left" },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Enable", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string", default: "null" },
              { label: "Link", name: "link", widget: "string", default: "null" } ] } ] }
      - file: "data/de/dreiSaeulen.yml"
        label: "Drei S채ulen"
        name: "dreisaeulen"
        fields:
          - { label: "S채ulen", name: "saeule", widget: "object", fields: [
            { label: "Activ", name: "enable", widget: "boolean", default: true },
            { label: "Headline", name: "title", widget: "string" },
            { label: "S채ulen", name: "saeulen_item",  widget: "list", fields: [
              { label: "Titel", name: "title", widget: "string" },
              { label: "Content", name: "content", widget: "markdown" } ] } ] }
      - file: "data/de/cta_contact.yml"
        label: "CTA Kontakt"
        name: "calltoactionContact"
        fields:
          - { label: "Call to action", name: "cta_contact", widget: "object", fields: [
            { label: "Active", name: "enable", widget: "boolean", default: true },
            { label: "Hintergrund", name: "bg_image", widget: "image" },
            { label: "Content", name: "content", widget: "markdown" },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Active", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" } ] } ] }
      - file: "data/de/infrastruktur.yml"
        label: "Infrastruktur"
        name: "infrastruktur"
        fields:
          - { label: "Infrastruktur", name: "infrastruktur", widget: "object", fields: [
            { label: "Active", name: "enable", widget: "boolean", default: true },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" },
            { label: "Punkte", name: "feature_item",  widget: "list", fields: [
              { label: "Titel", name: "title", widget: "string" },
              { label: "Content", name: "content", widget: "markdown" } ] } ] }
      - file: "data/de/cta_termin.yml"
        label: "CTA Termin"
        name: "calltoactionTermin"
        fields:
          - { label: "Call to action", name: "cta_termin", widget: "object", fields: [
            { label: "Active", name: "enable", widget: "boolean", default: true },
            { label: "Hintergrund", name: "bg_image", widget: "image" },
            { label: "Content", name: "content", widget: "markdown" },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Active", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" } ] } ] }
      - file: "data/de/kundenstimme.yml"
        label: "Kundenstimme"
        name: "kundenstimme"
        fields:
          - { label: "Kundenstimme", name: "kundenstimme", widget: "object", fields: [
            { label: "Active", name: "enable", widget: "boolean", default: true },
            { label: "Hintergrund", name: "bg_image", widget: "image" },
            { label: "Kunden", name: "testimonial_item", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string"},
              { label: "Bild", name: "image", widget: "image" },
              { label: "Content", name: "content", widget: "text" } ] } ] }
      - file: "data/de/mediathek.yml"
        label: "Mediathek Teaser"
        name: "mediathekTeaser"
        fields:
          - { label: "Mediathek Teaser", name: "mediathekTeaser", widget: "object", fields: [
            { label: "Titel", name: "title", widget: "string" },
            { label: "Content", name: "content", widget: "text" },
            { label: "Button", name: "button", widget: "object", fields: [
              { label: "Aktive", name: "enable", widget: "boolean", default: true },
              { label: "Label", name: "label", widget: "string" },
              { label: "Link", name: "link", widget: "string" } ] } ] }
  - name: "megamenu"
    label: "Mega Menu"
    files:
      - file: "data/de/megamenu.yml"
        label: "Subline Megamenu"
        name: "sublineMegamenu"
        fields:
          - { label: "Submenu", name: "submenu", widget: "list", fields: [
            { label: "Name, nicht 채ndern!", name: "name", widget: "string"},
            { label: "Subline", name: "content", widget: "string"}]}
  - name: "zentraleIt"
    label: "Zentrale It"
    files:
      - file: "data/de/serve.yml"
        label: "Server"
        name: "server"
        fields:
          - { label: "Headline", name: "headline", widget: "string"}
          - { label: "Content", name: "content", widget: "markdown"}
          - { label: "Image", name: "img", widget: "image"}
          - { label: "Button", name: "button", widget: "object", fields: [
              {label: "Aktive", name: "enable", widget: "boolean", default: true},
              {label: "Label", name: "label", widget: "string"},
              {label: "Link", name: "link", widget: "string"}]}
          - { label: "Logos", name: "logos", widget: "list", fields: [
              {label: "Logo", name: "logo", widget: "image"}]}
          - { label: "Boxes", name: "boxes", widget: "list", fields: [
              { label: "Headline", name: "headline", widget: "image" },
              { label: "Content", name: "content", widget: "image" }]}
  - name: "unternehmensseite"
    label: "Unternehmensseite"
    files:
      - file: "content/deutsch/unternehmen/_index.md"
        name: "banner"
        label: "Banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" } ] }
  - name: "karriere"
    label: "Karriereseite"
    files:
      - file: "content/deutsch/karriere/_index.md"
        name: "banner"
        label: "Banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" } ] }
      - file: "data/de/karriere_left.yml"
        name: "textLinks"
        label: "Unternehmen"
        fields:
          - { label: "Unternehmen", name: "unternehmen", widget: "object", fields: [
              { label: "Headline", name: "headline", widget: "string" },
              { label: "Content", name: "content", widget: "markdown" } ] }
          - { label: "Benefits", name: "benefits", widget: "object", fields: [
              { label: "Headline", name: "headline", widget: "string" },
              { label: "Items", name: "items", widget: "list", fields: [
                { label: "Benefit", name: "title", widget: "string" }] } ] }
          - { label: "Text unter Jobs", name: "subcontent", widget: "object", fields: [
            { label: "Content", name: "content", widget: "markdown" } ] }
      - file: "data/de/jobs.yml"
        name: "jobs"
        label: "Jobs"
        fields:
          - { label: "Jobs", name: "jobs", widget: "object", fields: [
            { label: "Items", name: "items", widget: "list", fields: [
              { label: "Job Titel", name: "title", widget: "string" },
              { label: "Beschreibung", name: "description", widget: "markdown" }] } ] }
  - name: "kontaktseite"
    label: "Kontaktseite"
    files:
      - file: "content/deutsch/kontakt/_index.md"
        name: "banner"
        label: "Banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" } ] }
      - file: "data/de/contactForm.yml"
        label: "Kontakt Formular"
        name: "kontaktformular"
        fields:
          - { label: "Kontakt", name: "contact", widget: "object", fields: [
            { label: "Titel", name: "title", widget: "string" },
            { label: "Niederlassung Eins", name: "niederlassung", widget: "object", fields: [
              { label: "Aktiv", name: "enable", widget: "boolean" },
              { label: "Headline Kontakt Adresse", name: "headline_contact_list", widget: "string" },
              { label: "Strasse", name: "strasse", widget: "string" },
              { label: "Ort", name: "ort", widget: "string" },
              { label: "Kontakt List", name: "contact_list", widget: "list", fields: [
                { label: "Info", name: "info", widget: "string" } ] } ] },
            { label: "Niederlassung Zwei", name: "niederlassung_2", widget: "object", fields: [
              { label: "Aktiv", name: "enable", widget: "boolean" },
              { label: "Headline Kontakt Adresse", name: "headline_contact_list", widget: "string" },
              { label: "Strasse", name: "strasse", widget: "string" },
              { label: "Ort", name: "ort", widget: "string" },
              { label: "Kontakt List", name: "contact_list", widget: "list", fields: [
                { label: "Info", name: "info", widget: "string" } ] } ] },
            { label: "Text Rechts", name: "conctact_support", widget: "object", fields: [
              { label: "Headline", name: "headline", widget: "string" },
              { label: "Text", name: "content", widget: "text" },
              { label: "Button", name: "button", widget: "object", fields: [
                { label: "Enable", name: "enable", widget: "boolean" },
                { label: "Label", name: "lable", widget: "string" },
                { label: "Link", name: "link", widget: "string" } ] } ] } ] }
  - name: "support"
    label: "Supportseite"
    files:
      - file: "content/deutsch/support/_index.md"
        name: "banner"
        label: "Banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" } ] }
      - file: "data/de/linkerKasten.yml"
        name: "linkerkasten"
        label: "Linker Kasten"
        fields:
          - { label: "Linker Kasten", name: "linke_box", widget: "object", fields: [
            { label: "Headline", name: "headline", widget: "string" },
            { label: "Text", name: "copy", widget: "string" },
            { label: "Service Email Vertragskunde Titel", name: "headlineservice", widget: "string" },
            { label: "Service Email Vertragskunde Adresse", name: "servicevertragskundenemail", widget: "string" },
            { label: "Service Email Aktive", name: "serviceemailenable", widget: "boolean" },
            { label: "Service Email Titel", name: "serviceemailHeadline", widget: "string" },
            { label: "Service Email Adresse", name: "serviceemail", widget: "string" },
            { label: "Service Tel Headline", name: "servicetelHeadline", widget: "string" },
            { label: "Service Tel", name: "servicetel", widget: "string" },
            { label: "Buttons", name: "buttons", widget: "list", fields: [
              { label: "Text Button", name: "name", widget: "string" },
              { label: "Link", name: "link", widget: "string" } ] } ] }
      - file: "data/de/rechterKasten.yml"
        name: "rechterkasten"
        label: "Rechter Kasten"
        fields:
        - { label: "Rechter Kasten", name: "rechte_box", widget: "object", fields: [
          { label: "Headline", name: "headline", widget: "string" },
          { label: "Text", name: "copy", widget: "string" },
          { label: "Service Email Titel", name: "softwareservicemailHeadline", widget: "string" },
          { label: "Service Email Adresse", name: "softwareservicemail", widget: "string" },
          { label: "Service Tel Titel", name: "softwareservicetelHeadline", widget: "string" },
          { label: "Service Tel Nummer", name: "softwareservicetel", widget: "string" },
          { label: "Buttons", name: "buttons", widget: "list", fields: [
            { label: "Text Button", name: "name", widget: "string" },
            { label: "Link", name: "link", widget: "string" } ] } ] }
  - name: "terminbuchen"
    label: "Termin buchen"
    files:
      - file: "content/deutsch/termin/_index.md"
        label: "Banner"
        name: "banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" } ] }
  - name: "extras"
    label: "Extras"
    files:
      - file: "data/de/sideNavi.yml"
        label: "Sidebar"
        name: "sidebar"
        fields:
          - { label: "Kontakt", name: "kontakt", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Label", name: "lable", widget: "string" },
              { label: "Ist eine Telefonnummer", name: "tel", widget: "boolean", default: false },
              { label: "Link", name: "link", widget: "string" }]}
  - name: "mediathek"
    label: "Mediathek"
    files:
      - file: "content/deutsch/mediathek/_index.md"
        name: "banner"
        label: "Banner"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
            { label: "Hintergrundbild", name: "bg_image", widget: "image" },
            { label: "Titel", name: "title", widget: "string" },
            { label: "Subline", name: "content", widget: "string" } ] }
      - file: "data/de/mediathek.yml"
        label: "Mediathek Info"
        name: "mediathekInfo"
        fields:
          - { label: "Mediathek", name: "mediathekFull", widget: "object", fields: [
              {label: "Title", name: "title", widget: "string" },
              {label: "Content", name: "content", widget: "string" }]}
      - file: "data/de/mediathekVideos.yml"
        label: "Mediathek Videos"
        name: "mediathekVideos"
        fields:
          - {label: "Videos", name: "videos", widget: "list", fields: [
              { label: "Teaser", name: "teaser", widget: "boolean", default: false},
              { label: "Title", name: "title", widget: "string" },
              { label: "Content", name: "summary", widget: "string" },
              { label: "Code", name: "code", widget: "string" },
              { label: "Kategorie", name: "categories", widget: "list", default: ["K-1", "K-2"] },
              { label: "Link", name: "link", widget: "hidden", default: "https://www.youtube.com/embed/"},
              { label: "controllsSmall", name: "controllsSmall", widget: "hidden", default: "?theme=dark&mute=1&controls=0&rel=0&cc_load_policy=0&origin"},
              { label: "controllsLarge", name: "controllsLarge", widget: "hidden", default: "?theme=dark&keyboard=1&showinfo=0&disablekb=1&modestbranding=1&mute=0"}]}
