backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
collections:
  - name: "slider"
    label: "Slider"
    folder: "content/deutsch/slides"
    create: true
    fields:
      - { label: "Draft", name: "enable", widget: "boolean", default: true }
      - { label: "Image", name: "bg_image", widget: "image" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "string" }
      - { label: "Animation from", name: "animation_from", widget: "string", default: "left" }
      - label: "Button"
        name: "button"
        fields:
          - label: "Enable"
            name: "enable"
            widget: "boolean"
            default: true
          - label: "Label"
            name: "label"
            widget: "string"
          - label: "Link"
            name: "link"
            widget: "string"


