backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "images/uploads"
collections:
  - name: "slider"
    label: "Slider"
    folder: "content/deutsch/slides"
    create: true
    fields:
      - { label: "Draft", name: "enable", widget: "boolean", default: true }
      - { label: "Background", name: "bg_image", widget: "image" }
      - { label: "Produkt", name: "hero_image", widget: "image" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "string" }
      - { label: "Animation from", name: "animation_from", widget: "string", default: "left" }
      - { label: "Button", name: "button", widget: "object", fields: [
          { label: "Enable", name: "enable", widget: "boolean", default: true },
          { label: "Label", name: "label", widget: "string" },
          { label: "Link", name: "link", widget: "string" }]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/deutsch/support/_index.md"
        name: "support"
        label: "Support Page"
        fields:
          - { label: "Banner", name: "banner", widget: "object", fields: [
              { label: "Hintergrundbild", name: "bg_image", widget: "image"},
              { label: "Titel", name: "title", widget: "string"},
              { label: "Subline", name: "content", widget: "string" }
          ]}
          - { label: "Linker Kasten", name: "linke_box", widget: "object", fields: [
              { label: "Headline", name: "headline", widget: "string"},
              { label: "Text", name: "copy", widget: "string"},
              { label: "Service Email VK Headline", name: "headlineservice", widget: "string"},
              { label: "Service Email VK", name: "servicevertragskundenemail", widget: "string"},
              { label: "Service Email Headline", name: "serviceemailHeadline", widget: "string"},
              { label: "Service Email", name: "serviceemail", widget: "string"},
              { label: "Service Tel Headline", name: "servicetelHeadline", widget: "string"},
              { label: "Service Tel", name: "servicetel", widget: "string"},
              { label: "Buttons", name: "buttons", widget: "list", fields: [
                { label: "Text Button", name: "name", widget: "string" },
                { label: "Link", name: "link", widget: "string" }]
              }
          ]}
          - { label: "Rechter Kasten", name: "rechte_box", widget: "object", fields: [
              { label: "Headline", name: "headline", widget: "string" },
              { label: "Text", name: "copy", widget: "string" },
              { label: "Service Email Headline", name: "softwareservicemailHeadline", widget: "string" },
              { label: "Service Email", name: "softwareservicemail", widget: "string" },
              { label: "Service Tel Headline", name: "softwareservicetelHeadline", widget: "string" },
              { label: "Service Tel", name: "softwareservicetel", widget: "string" },
              { label: "Buttons", name: "buttons", widget: "list", fields: [
                { label: "Text Button", name: "name", widget: "string" },
                { label: "Link", name: "link", widget: "string" }]
              }
          ]}
  - name: "modules"
    label: "Modules"
    files:
      - file: "data/de/sideNavi.yml"
        label: "Sidebar"
        name: "sidebar"
        fields:
          - { label: "Kontakt", name: "kontakt", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Label", name: "lable", widget: "string" },
              { label: "Ist eine Telefonnummer", name: "tel", widget: "boolean", default: false },
              { label: "Link", name: "link", widget: "string" },]}
      - file: "data/de/contactForm.yml"
        label: "Kontakt Formular"
        name: "kontaktformular"
        fields:
          - { label: "Kontakt", name: "contact", widget: "object", fields: [
              { label: "Titel", name: "title", widget: "string" },
              { label: "Niederlassung Eins", name: "niederlassung", widget: "object", fields: [
                { label: "Headline Kontakt Adresse", name: "headline_contact_list", widget: "string" },
                { label: "Strasse", name: "strasse", widget: "string"},
                { label: "Ort", name: "ort", widget: "string" },
                { label: "Kontakt List", name: "contact_list", widget: "list", fields: [
                  { label: "Info", name: "info", widget: "string" }]}]},
            { label: "Niederlassung Zwei", name: "niederlassung_2", widget: "object", fields: [
              { label: "Aktiv", name: "enable", widget: "boolean" },
              { label: "Headline Kontakt Adresse", name: "headline_contact_list", widget: "string" },
              { label: "Strasse", name: "strasse", widget: "string" },
              { label: "Ort", name: "ort", widget: "string" },
              { label: "Kontakt List", name: "contact_list", widget: "list", fields: [
                { label: "Info", name: "info", widget: "string" } ] } ] },
              { label: "Support Text", name: "conctact_support", widget: "object", fields: [
                { label: "Headline", name: "headline", widget: "string" },
                { label: "Text", name: "content", widget: "text" },
                { label: "Button", name: "button", widget: "object", fields: [
                  { label: "Enable", name: "enable", widget: "boolean" },
                  { label: "Label", name: "lable", widget: "string" },
                  { label: "Link", name: "link", widget: "string" }]}]}]}
      - file: "data/de/cta.yml"
        label: "Call To Action"
        name: "calltoaction"
        fields:
          - { label: "CTA", name: "cta", widget: "object", fields: [
              { label: "Activ", name: "enable", widget: "boolean", default: true },
              { label: "Headline", name: "title", widget: "string" },
              { label: "Subline", name: "content", widget: "string" },
              { label: "Button", name: "button", widget: "object", fields: [
                { label: "Activ", name: "enable", widget: "boolean", default: true },
                { label: "Label", name: "label", widget: "string" },
                { label: "Link", name: "link", widget: "string" }]}] }
      - file: "data/de/dreiSaeulen.yml"
        label: "Drei Säulen"
        name: "dreisaeulen"
        fields:
          - { label: "Säulen", name: "saeule", widget: "object", fields: [
              { label: "Activ", name: "enable", widget: "boolean", default: true },
              { label: "Headline", name: "title", widget: "string" },
              { label: "Säulen", name: "saeulen_item",  widget: "list", fields: [
                { label: "Titel", name: "title", widget: "string" },
                { label: "Content", name: "content", widget: "text" } ] } ] }

