backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/english/_index.md"
        label: "Header"
        media_folder: "images/backgrounds/
        name: "home"
        fields:
          - { label: "Enable", name: "enable", widget: "boolean", default: true }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "ButtonText", name: "label", widget: "string" }
          - { label: "Image Mobile", name: "bg_image_webp", widget: "image" }
          - { label: "Image Desktop", name: "bg_image", widget: "image" }
          - { label: "Content", name: "content", widget: "string" }

